revert

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -3,24 +3,27 @@ name: 'Terraform Plan/Apply'
 on:
   push:
     branches:
-      - master
+    - master
   pull_request:
     branches:
-      - master
+    - master
+#ffdfdfdfdf
 
+#Special permissions required for OIDC authentication
 permissions:
   id-token: write
   contents: write
   pull-requests: write
 
+#These environment variables are used by the terraform azure provider to setup OIDD authenticate. 
 env:
-  ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
-  ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
-  ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
-  ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
-  TF_VAR_ssh: ${{ secrets.K8S_SSH_PUBLIC }}
+  ARM_CLIENT_ID: "${{ secrets.AZURE_CLIENT_ID }}"
+  ARM_CLIENT_SECRET: "${{ secrets.AZURE_CLIENT_SECRET }}"
+  ARM_SUBSCRIPTION_ID: "${{ secrets.AZURE_SUBSCRIPTION_ID }}"
+  ARM_TENANT_ID: "${{ secrets.AZURE_TENANT_ID }}"
+  TF_VAR_ssh: "${{ secrets.K8S_SSH_PUBLIC }}"
   GH_PAT: ${{ secrets.GH_PAT }}
-  SSH_PASSWORD: ${{ secrets.SSH_PASSWORD }}
+  SSH_PASSWORD: ${{ secrets.SSH_PASSWORD }}  
 
 jobs:
   unit-test:
@@ -62,71 +65,91 @@ jobs:
     runs-on: ubuntu-latest
     needs: [unit-test]
     env:
+      #this is needed since we are running terraform with read-only permissions
       ARM_SKIP_PROVIDER_REGISTRATION: true
     outputs:
       tfplanExitCode: ${{ steps.tf-plan.outputs.exitcode }}
 
+
     steps:
-      - name: Checkout
-        uses: actions/checkout@v3
+   
+     
+    - name: Checkout
+      uses: actions/checkout@v3
 
-      - name: Setup Terraform
-        uses: hashicorp/setup-terraform@v2
-        with:
-          terraform_wrapper: false
+    # Install the latest version of the Terraform CLI
+    - name: Setup Terraform
+      uses: hashicorp/setup-terraform@v2
+      with:
+        terraform_wrapper: false
 
-      - name: Terraform Init
-        run: terraform init
+    # Initialize a new or existing Terraform working directory by creating initial files, loading any remote state, downloading modules, etc.
+    - name: Terraform Init
+      run: terraform init
+      
+    # Checks that all Terraform configuration files adhere to a canonical format
+    # Will fail the build if not
+    # - name: Terraform Format
+    #   
+    #   run: terraform fmt -check
 
-      - name: Terraform Plan
-        id: tf-plan
-        run: |
-          export exitcode=0
-          terraform plan -detailed-exitcode -no-color -out tfplan || export exitcode=$?
+    # Generates an execution plan for Terraform
+    # An exit code of 0 indicated no changes, 1 a terraform failure, 2 there are pending changes.
+    - name: Terraform Plan
+      id: tf-plan
+      
+      run: |
+        export exitcode=0
+        terraform plan -detailed-exitcode -no-color -out tfplan || export exitcode=$?
 
-          echo "exitcode=$exitcode" >> $GITHUB_OUTPUT
-
-          if [ $exitcode -eq 1 ]; then
-            echo Terraform Plan Failed!
-            exit 1
-          else 
-            exit 0
-          fi
-
-      - name: Publish Terraform Plan
-        uses: actions/upload-artifact@v3
-        with:
-          name: tfplan
-          path: ./tfplan
-
-      - name: Create String Output
-        id: tf-plan-string
-        run: |
-          TERRAFORM_PLAN=$(terraform show -no-color tfplan)
-          
-          delimiter="$(openssl rand -hex 8)"
-          echo "summary<<${delimiter}" >> $GITHUB_OUTPUT
-          echo "## Terraform Plan Output" >> $GITHUB_OUTPUT
-          echo "<details><summary>Click to expand</summary>" >> $GITHUB_OUTPUT
-          echo "" >> $GITHUB_OUTPUT
-          echo '```terraform' >> $GITHUB_OUTPUT
-          echo "$TERRAFORM_PLAN" >> $GITHUB_OUTPUT
-          echo '```' >> $GITHUB_OUTPUT
-          echo "</details>" >> $GITHUB_OUTPUT
-          echo "${delimiter}" >> $GITHUB_OUTPUT
-
-      - name: Publish Terraform Plan to Task Summary
-        env:
-          SUMMARY: ${{ steps.tf-plan-string.outputs.summary }}
-        run: |
-          echo "$SUMMARY" >> $GITHUB_STEP_SUMMARY
-
-      - name: Push Terraform Output to PR
-        if: github.ref != 'refs/heads/master'
-        uses: actions/github-script@v6
-        env:
-          SUMMARY: "${{ steps.tf-plan-string.outputs.summary }}"
-        with:
+        echo "exitcode=$exitcode" >> $GITHUB_OUTPUT
+        
+        if [ $exitcode -eq 1 ]; then
+          echo Terraform Plan Failed!
+          exit 1
+        else 
+          exit 0
+        fi
+        
+    # Save plan to artifacts  
+    - name: Publish Terraform Plan
+      uses: actions/upload-artifact@v3
+      with:
+        name: tfplan
+        path: ./tfplan
+        
+    # Create string output of Terraform Plan
+    - name: Create String Output
+      id: tf-plan-string
+      
+      run: |
+        TERRAFORM_PLAN=$(terraform show -no-color tfplan)
+        
+        delimiter="$(openssl rand -hex 8)"
+        echo "summary<<${delimiter}" >> $GITHUB_OUTPUT
+        echo "## Terraform Plan Output" >> $GITHUB_OUTPUT
+        echo "<details><summary>Click to expand</summary>" >> $GITHUB_OUTPUT
+        echo "" >> $GITHUB_OUTPUT
+        echo '```terraform' >> $GITHUB_OUTPUT
+        echo "$TERRAFORM_PLAN" >> $GITHUB_OUTPUT
+        echo '```' >> $GITHUB_OUTPUT
+        echo "</details>" >> $GITHUB_OUTPUT
+        echo "${delimiter}" >> $GITHUB_OUTPUT
+        
+    # Publish Terraform Plan as task summary
+    - name: Publish Terraform Plan to Task Summary
+      env:
+        SUMMARY: ${{ steps.tf-plan-string.outputs.summary }}
+      run: |
+        echo "$SUMMARY" >> $GITHUB_STEP_SUMMARY
+      
+    # If this is a PR post the changes
+    - name: Push Terraform Output to PR
+      if: github.ref != 'refs/heads/master'
+      uses: actions/github-script@v6
+      env:
+        SUMMARY: "${{ steps.tf-plan-string.outputs.summary }}"
+      with:
           github-token: ${{ secrets.GITHUB_TOKEN }}
           script: |
             const body = `${process.env.SUMMARY}`;
@@ -136,29 +159,144 @@ jobs:
                 repo: context.repo.repo,
                 body: body
             })
-
+                
   terraform-apply:
     name: 'Terraform Apply'
+    # if: github.ref == 'refs/heads/master' && needs.terraform-plan.outputs.tfplanExitCode == 2
     runs-on: ubuntu-latest
+    environment: production
     needs: [terraform-plan]
     outputs:
       pub-ip: ${{ steps.pub-ip.outputs.pub-ip }}
+    
+    steps:
+    # Checkout the repository to the GitHub Actions runner
+    - name: Checkout
+      uses: actions/checkout@v3
+
+    # Install the latest version of Terraform CLI and configure the Terraform CLI configuration file with a Terraform Cloud user API token
+    - name: Setup Terraform
+      uses: hashicorp/setup-terraform@v2
+    
+
+    # Initialize a new or existing Terraform working directory by creating initial files, loading any remote state, downloading modules, etc.
+    - name: Terraform Init
+      
+      run: terraform init
+
+    # Download saved plan from artifacts  
+    - name: Download Terraform Plan
+      uses: actions/download-artifact@v3
+      with:
+        name: tfplan
+        path: .
+
+    # Terraform Apply
+    - name: Terraform Apply
+      
+      run: terraform apply -auto-approve tfplan
+  # use script
+  parsing-ip:
+    runs-on: ubuntu-latest
+    needs: [terraform-apply]
+    steps:
+    - name: Checkout code
+      uses: actions/checkout@v2
+
+    - name: Setup Python
+      uses: actions/setup-python@v2
+      with:
+        python-version: 3.9  
+
+    #- name: Install Azure CLI
+    #  run: |
+    #    curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash
+    #    az extension add --name vmss
+    - name: Azure Login
+      run: |
+        az login --service-principal -u ${{ secrets.AZURE_CLIENT_ID }} -p ${{ secrets.AZURE_CLIENT_SECRET }} --tenant ${{ secrets.AZURE_TENANT_ID }}
+      env:
+        ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
+      shell: bash
+
+    - name: List VMSS Instance Public IPs
+      run: |
+        az vmss list-instance-public-ips --name example-vmss --resource-group azure-resource_group | python3 parser.py > ip.txt
+      working-directory: ${{ github.workspace }}
+
+    - name: Append IPs to host.txt
+      run: |
+        python3 iphost.py >> host.txt
+      working-directory: ${{ github.workspace }}
+    
+    - name: Commit and Push Changes
+      run: |
+        git config --global user.email "gajdaryura@gmail.com"
+        git config --global user.name "Yur4ik1234"
+        git add ip.txt host.txt
+        git commit -m "Update IPs"
+        git push https://$GH_PAT@github.com/Yur4ik1234/auto-cifar10.git HEAD:master
+      env: 
+        GH_PAT: ${{ secrets.GH_PAT }}  
+      working-directory: ${{ github.workspace }}
+    
+  
+  ansible-deploy:
+    name: 'Deploy Ansible Playbook'
+    runs-on: ubuntu-latest
+    needs: [parsing-ip]  # This job depends on the "deploy" job, which prepares your inventory file
 
     steps:
-      - name: Checkout
-        uses: actions/checkout@v3
+      - name: Checkout code
+        uses: actions/checkout@v2
 
-      - name: Setup Terraform
-        uses: hashicorp/setup-terraform@v2
+      - name: Set up SSH key
+        run: |
+          echo "$SSH_PRIVATE_KEY" > ansible_ssh_key
+          chmod 600 ansible_ssh_key
+        env:
+          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}  # Define this secret with your SSH private key
 
-      - name: Terraform Init
-        run: terraform init
+      - name: Run Ansible playbook
+        run: |
+          ansible-playbook -i host.txt -u adminuser --extra-vars "ansible_ssh_password=${{ secrets.SSH_PASSWORD }}" ansible/playbook.yaml --force
 
-      - name: Download Terraform Plan
-        uses: actions/download-artifact@v3
-        with:
-          name: tfplan
-          path: .
+  
+  
+    # deploying ansible 
+  #ansible-deploy:
+  #  name: 'Deploy ansible playbook'
+  #  runs-on: ubuntu-latest  
+  #  needs: [deploy]
+  #  steps:
+  #  - name: Checkout
+  #    uses: actions/checkout@v3
 
-      - name: Terraform Apply
-        run: terraform apply
+  #  - name: Create Ansible Inventory
+  #    run: |
+  #      echo "$(<host.txt)" > inventory.ini
+  #    working-directory: ${{ github.workspace }}
+  #  - name: Set up inventory
+  #    run: echo '::set-output name=inventory::$(cat host.txt)'
+
+  #  - name: Run playbook
+  #    uses: dawidd6/action-ansible-playbook@v2
+  #    with:
+        # Required, playbook filepath
+  #      playbook: ansible/playbook.yaml
+        # Optional, directory where playbooks live
+        #directory: ./
+        # Optional, SSH private key
+  #      key: ${{secrets.SSH_PRIVATE_KEY}}
+        # Optional, literal inventory file contents
+        #inventory: |
+        #  vm1.deploy-vmsc-ubuntu.westeurope.cloudapp.azure.com ansible_become=yes ansible_ssh_user=adminuser
+        #  vm0.deploy-vmsc-ubuntu.westeurope.cloudapp.azure.com ansible_become=yes ansible_ssh_user=adminuser
+          
+        #inventory: ${{ steps.set-up-inventory.outputs.inventory }}
+  #      inventory: |
+  #        13.80.129.170 ansible_become=yes ansible_ssh_user=adminuser 
+
+        
+          
+          
